Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [1]:
import numpy as np

In [2]:
def mov_avg(arr,n,k):
    
    i=0
    moving_average= np.array([])
    while i < len(arr)-k+1:
        cur_window= arr[i:i+k]
        cur_window_avg= sum(cur_window)/k
        moving_average= np.append(moving_average,cur_window_avg)
        i+=1
    return moving_average 

In [3]:
arr= list(map(int,input().strip().split(',')))
n= len(arr)
k= int(input("Enter the window size: "))

result= mov_avg(arr,n,k)

print(result)

3,5,7,2,8,10,11,65,72,81,99,100,150
Enter the window size: 3
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [4]:
def vandermonde_matrix(array, n, increasing=False):
    
    if not increasing:
        op = np.array([x**(n-1-i) for x in array for i in range(n)]).reshape(array.size,n)
    elif increasing:
        op = np.array([x**i for x in array for i in range(n)]).reshape(array.size,n)
    
    return op

In [5]:
inp= np.array([1,3,7,5,6])
no_columns= int(input("Enter the no of columns needed in the output matrix: "))
out_power_not_increasing= vandermonde_matrix(inp,no_columns,False)
out_power_increasing= vandermonde_matrix(inp,no_columns,True)

Enter the no of columns needed in the output matrix: 3


In [6]:
print("The vandermonde matrix with powers are not increasing:\n",out_power_not_increasing)
print("The vandermonde matrix with powers are increasing:\n",out_power_increasing)

The vandermonde matrix with powers are not increasing:
 [[ 1  1  1]
 [ 9  3  1]
 [49  7  1]
 [25  5  1]
 [36  6  1]]
The vandermonde matrix with powers are increasing:
 [[ 1  1  1]
 [ 1  3  9]
 [ 1  7 49]
 [ 1  5 25]
 [ 1  6 36]]
